"""P4.1 — Workspace Runtime manifest loader tests.

Read-only foundation: these tests assert the models and loaders parse valid
manifests, resolve in the workspace → projects → repositories order, fail closed on
malformed input, and — the backward-compatibility guarantee — load a workspace
generated by the P3 bootstrap unchanged.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from projectos.domain.errors import NotFoundError, ValidationError
from projectos.infrastructure.workspace import bootstrap_workspace
from projectos.infrastructure.workspace_manifest import (
    ProjectManifest,
    ProjectRepository,
    WorkspaceManifest,
    load_project_manifest,
    load_workspace_manifest,
    resolve_workspace,
)


def write(path: Path, data: dict) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.dump(data, sort_keys=False), encoding="utf-8")
    return path


VALID_WORKSPACE = {
    "schema_version": 1,
    "workspace": {"name": "Acme"},
    "projectos": "ProjectOS",
    "shared": {"packs": "Shared/Packs", "knowledge": "Shared/Knowledge"},
    "packs": [{"name": "rapid-build", "path": "Shared/Packs/rapid-build"}],
    "projects": [{"name": "Alpha", "path": "Projects/Alpha"}],
}

VALID_PROJECT = {
    "schema_version": 1,
    "project": {"id": "alpha", "name": "Alpha", "description": "First project."},
    "pack": "rapid-build",
}


# -- backward compatibility (P3) ----------------------------------------------


def test_p3_generated_workspace_loads_unchanged(tmp_path: Path) -> None:
    """The headline guarantee: an existing P3 workspace continues to function."""
    root = tmp_path / "WS"
    bootstrap_workspace(root, name="Demo")

    workspace = resolve_workspace(root)

    assert workspace.manifest.name == "Demo"
    assert len(workspace.manifest.packs) == 7
    assert [p.ref.name for p in workspace.projects] == ["ExampleProject"]
    example = workspace.projects[0]
    assert example.manifest.id == "example-project"
    assert example.manifest.pack == "rapid-build"
    # P3 project.yaml has no repository — the new optional field is absent, not an error.
    assert example.repository is None


# -- workspace manifest -------------------------------------------------------


def test_valid_workspace_manifest_loads(tmp_path: Path) -> None:
    path = write(tmp_path / "Workspace.yaml", VALID_WORKSPACE)
    manifest = load_workspace_manifest(path)

    assert manifest.name == "Acme"
    assert manifest.projectos == "ProjectOS"
    assert manifest.shared.packs == "Shared/Packs"
    assert manifest.shared.templates is None  # optional, absent
    assert manifest.packs[0].name == "rapid-build"
    assert manifest.project("Alpha") is not None
    assert manifest.project("Missing") is None


def test_workspace_minimal_manifest(tmp_path: Path) -> None:
    """Only schema_version and workspace.name are required; the rest is optional."""
    path = write(tmp_path / "Workspace.yaml", {"schema_version": 1, "workspace": {"name": "Min"}})
    manifest = load_workspace_manifest(path)

    assert manifest.name == "Min"
    assert manifest.projects == ()
    assert manifest.packs == ()
    assert manifest.projectos is None


def test_workspace_missing_name_is_rejected(tmp_path: Path) -> None:
    path = write(tmp_path / "Workspace.yaml", {"schema_version": 1, "workspace": {}})
    with pytest.raises(ValidationError, match="Schema validation failed"):
        load_workspace_manifest(path)


def test_workspace_unknown_field_is_rejected(tmp_path: Path) -> None:
    path = write(tmp_path / "Workspace.yaml", {**VALID_WORKSPACE, "surprise": True})
    with pytest.raises(ValidationError, match="Schema validation failed"):
        load_workspace_manifest(path)


def test_workspace_wrong_schema_version_is_rejected(tmp_path: Path) -> None:
    path = write(tmp_path / "Workspace.yaml", {**VALID_WORKSPACE, "schema_version": 2})
    with pytest.raises(ValidationError):
        load_workspace_manifest(path)


def test_duplicate_project_names_are_rejected(tmp_path: Path) -> None:
    raw = {
        **VALID_WORKSPACE,
        "projects": [
            {"name": "Alpha", "path": "Projects/Alpha"},
            {"name": "Alpha", "path": "Projects/Alpha2"},
        ],
    }
    path = write(tmp_path / "Workspace.yaml", raw)
    with pytest.raises(ValidationError, match="Duplicate workspace project name"):
        load_workspace_manifest(path)


def test_workspace_not_a_mapping_is_rejected(tmp_path: Path) -> None:
    path = tmp_path / "Workspace.yaml"
    path.write_text("- just\n- a list\n", encoding="utf-8")
    with pytest.raises(ValidationError, match="must contain a YAML mapping"):
        load_workspace_manifest(path)


# -- project manifest ---------------------------------------------------------


def test_valid_project_manifest_loads(tmp_path: Path) -> None:
    path = write(tmp_path / "project.yaml", VALID_PROJECT)
    manifest = load_project_manifest(path)

    assert manifest.id == "alpha"
    assert manifest.name == "Alpha"
    assert manifest.pack == "rapid-build"
    assert manifest.repository is None  # optional


def test_project_repository_is_a_property_of_project(tmp_path: Path) -> None:
    """P4 design: repository is nested under the project and fully optional."""
    raw = {
        **VALID_PROJECT,
        "repository": {"adapter": "local_git", "default_branch": "main", "path": "."},
    }
    path = write(tmp_path / "project.yaml", raw)
    manifest = load_project_manifest(path)

    assert manifest.repository == ProjectRepository(
        adapter="local_git", default_branch="main", path="."
    )


def test_project_missing_id_is_rejected(tmp_path: Path) -> None:
    raw = {"schema_version": 1, "project": {"name": "Alpha"}}
    path = write(tmp_path / "project.yaml", raw)
    with pytest.raises(ValidationError, match="Schema validation failed"):
        load_project_manifest(path)


def test_project_id_must_be_kebab_case(tmp_path: Path) -> None:
    raw = {"schema_version": 1, "project": {"id": "Not Kebab", "name": "X"}}
    path = write(tmp_path / "project.yaml", raw)
    with pytest.raises(ValidationError):
        load_project_manifest(path)


def test_project_unknown_repository_adapter_is_rejected(tmp_path: Path) -> None:
    raw = {**VALID_PROJECT, "repository": {"adapter": "subversion"}}
    path = write(tmp_path / "project.yaml", raw)
    with pytest.raises(ValidationError):
        load_project_manifest(path)


def test_project_unknown_field_is_rejected(tmp_path: Path) -> None:
    path = write(tmp_path / "project.yaml", {**VALID_PROJECT, "extra": 1})
    with pytest.raises(ValidationError):
        load_project_manifest(path)


# -- resolution (workspace -> projects -> repositories) -----------------------


def test_resolution_order_reaches_repository_through_project(tmp_path: Path) -> None:
    root = tmp_path / "WS"
    write(root / "Workspace.yaml", VALID_WORKSPACE)
    write(
        root / "Projects" / "Alpha" / "project.yaml",
        {**VALID_PROJECT, "repository": {"adapter": "local_git", "path": "repos/alpha"}},
    )

    workspace = resolve_workspace(root)

    assert [p.ref.name for p in workspace.projects] == ["Alpha"]
    resolved = workspace.projects[0]
    assert resolved.repository is not None
    assert resolved.repository.adapter == "local_git"
    assert resolved.repository.path == "repos/alpha"


def test_resolve_missing_workspace_manifest(tmp_path: Path) -> None:
    with pytest.raises(NotFoundError, match="No workspace manifest"):
        resolve_workspace(tmp_path / "nope")


def test_resolve_registered_project_without_manifest_fails_closed(tmp_path: Path) -> None:
    root = tmp_path / "WS"
    write(root / "Workspace.yaml", VALID_WORKSPACE)
    # Alpha is registered but its project.yaml is absent.

    with pytest.raises(ValidationError, match="is missing"):
        resolve_workspace(root)


def test_workspace_with_no_projects_resolves_empty(tmp_path: Path) -> None:
    root = tmp_path / "WS"
    write(root / "Workspace.yaml", {"schema_version": 1, "workspace": {"name": "Empty"}})

    workspace = resolve_workspace(root)

    assert workspace.projects == ()


# -- model construction (fail-closed cross-field rules) -----------------------


def test_workspace_manifest_rejects_bad_schema_version() -> None:
    with pytest.raises(ValidationError, match="Unsupported workspace schema_version"):
        WorkspaceManifest(schema_version=2, name="X")


def test_project_manifest_rejects_bad_schema_version() -> None:
    with pytest.raises(ValidationError, match="Unsupported project schema_version"):
        ProjectManifest(schema_version=9, id="x", name="X")
