"""Workspace Runtime foundation — read-only manifest models and loaders (P4.1).

The P3 bootstrap *writes* a workspace tree; this module *reads* it back into typed,
immutable values. It is deliberately read-only: it loads, schema-validates, and
constructs — it never writes, activates, or touches the ProjectOS kernel.

Resolution order is workspace → projects → repositories, as the P4 design requires:
:func:`resolve_workspace` loads the workspace manifest, then each registered
project, and a repository is reached only *through* a project (it is a property of
:class:`ProjectManifest`). Every field added by P4.1 is optional, so a workspace
generated by P3 — whose `project.yaml` carries no `repository` — loads unchanged.

Fail-closed: a manifest that fails its JSON Schema, is not a mapping, or breaks a
cross-field rule raises :class:`ValidationError`; nothing is silently defaulted.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from projectos.domain.errors import NotFoundError, ValidationError
from projectos.infrastructure.validation import validate
from projectos.infrastructure.workspace import WorkspaceLayout
from projectos.infrastructure.yaml_io import read_yaml

WORKSPACE_SCHEMA = "workspace_manifest.schema.json"
PROJECT_SCHEMA = "project_manifest.schema.json"


# -- workspace manifest ------------------------------------------------------


@dataclass(frozen=True, slots=True)
class SharedLocations:
    """Where the workspace keeps shared assets, relative to the workspace root.

    Every field is optional: a workspace need not declare a `shared` block at all.
    """

    packs: str | None = None
    templates: str | None = None
    policies: str | None = None
    prompts: str | None = None
    knowledge: str | None = None


@dataclass(frozen=True, slots=True)
class WorkspacePackRef:
    """A pack the workspace makes available, by name and path."""

    name: str
    path: str


@dataclass(frozen=True, slots=True)
class WorkspaceProjectRef:
    """A project registered in the workspace: a name and the path to its dir."""

    name: str
    path: str


@dataclass(frozen=True, slots=True)
class WorkspaceManifest:
    """The parsed `Workspace.yaml`. Immutable; construction validates cross-field
    rules the schema cannot express (unique project and pack names)."""

    schema_version: int
    name: str
    projectos: str | None = None
    shared: SharedLocations = SharedLocations()
    packs: tuple[WorkspacePackRef, ...] = ()
    projects: tuple[WorkspaceProjectRef, ...] = ()

    def __post_init__(self) -> None:
        if self.schema_version != 1:
            raise ValidationError(
                f"Unsupported workspace schema_version {self.schema_version}"
            )
        _reject_duplicates(
            (p.name for p in self.projects), what="workspace project name"
        )
        _reject_duplicates((p.name for p in self.packs), what="workspace pack name")

    def project(self, name: str) -> WorkspaceProjectRef | None:
        return next((p for p in self.projects if p.name == name), None)


# -- project manifest --------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ProjectRepository:
    """A project's repository. A property of the project (P4 design), and entirely
    optional — a project may declare none. Reading it is all P4.1 does; the kernel
    is unaffected."""

    adapter: str | None = None
    remote: str | None = None
    default_branch: str | None = None
    path: str | None = None


@dataclass(frozen=True, slots=True)
class ProjectManifest:
    """The parsed `Projects/<name>/project.yaml`. Immutable."""

    schema_version: int
    id: str
    name: str
    description: str = ""
    pack: str | None = None
    repository: ProjectRepository | None = None

    def __post_init__(self) -> None:
        if self.schema_version != 1:
            raise ValidationError(
                f"Unsupported project schema_version {self.schema_version}"
            )


# -- resolved aggregate ------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ResolvedProject:
    """A workspace project reference paired with its loaded manifest."""

    ref: WorkspaceProjectRef
    manifest: ProjectManifest

    @property
    def name(self) -> str:
        """The workspace registration name (the key in Workspace.yaml projects)."""
        return self.ref.name

    @property
    def project_id(self) -> str:
        """The project's own identifier, declared in its project.yaml."""
        return self.manifest.id

    @property
    def repository(self) -> ProjectRepository | None:
        """Repositories are resolved through projects (P4 resolution order)."""
        return self.manifest.repository


@dataclass(frozen=True, slots=True)
class Workspace:
    """A workspace manifest with its registered projects resolved.

    Construction rejects duplicate project identifiers so that lookup by identifier
    is unambiguous — two projects declaring the same `project.id` would make
    `by_id` non-deterministic, which is a fail-closed registration error.
    """

    root: Path
    manifest: WorkspaceManifest
    projects: tuple[ResolvedProject, ...] = ()

    def __post_init__(self) -> None:
        seen: set[str] = set()
        for project in self.projects:
            if project.project_id in seen:
                raise ValidationError(
                    f"Duplicate project identifier {project.project_id!r} in the workspace",
                    detail="Each registered project must declare a unique project.id.",
                )
            seen.add(project.project_id)

    def by_id(self, project_id: str) -> ResolvedProject | None:
        """Look up a resolved project by its `project.id` identifier."""
        return next((p for p in self.projects if p.project_id == project_id), None)

    def by_name(self, name: str) -> ResolvedProject | None:
        """Look up a resolved project by its workspace registration name."""
        return next((p for p in self.projects if p.name == name), None)


# -- loaders -----------------------------------------------------------------


def load_workspace_manifest(path: Path) -> WorkspaceManifest:
    """Load and validate a `Workspace.yaml`. Fail-closed."""
    raw = _require_mapping(read_yaml(path), source=str(path))
    validate(raw, WORKSPACE_SCHEMA, source=str(path))

    shared_raw = raw.get("shared", {})
    return WorkspaceManifest(
        schema_version=raw["schema_version"],
        name=raw["workspace"]["name"],
        projectos=raw.get("projectos"),
        shared=SharedLocations(
            packs=shared_raw.get("packs"),
            templates=shared_raw.get("templates"),
            policies=shared_raw.get("policies"),
            prompts=shared_raw.get("prompts"),
            knowledge=shared_raw.get("knowledge"),
        ),
        packs=tuple(
            WorkspacePackRef(p["name"], p["path"]) for p in raw.get("packs", [])
        ),
        projects=tuple(
            WorkspaceProjectRef(p["name"], p["path"]) for p in raw.get("projects", [])
        ),
    )


def load_project_manifest(path: Path) -> ProjectManifest:
    """Load and validate a `project.yaml`. Fail-closed."""
    raw = _require_mapping(read_yaml(path), source=str(path))
    validate(raw, PROJECT_SCHEMA, source=str(path))

    project = raw["project"]
    repository = None
    repo_raw = raw.get("repository")
    if repo_raw is not None:
        repository = ProjectRepository(
            adapter=repo_raw.get("adapter"),
            remote=repo_raw.get("remote"),
            default_branch=repo_raw.get("default_branch"),
            path=repo_raw.get("path"),
        )

    return ProjectManifest(
        schema_version=raw["schema_version"],
        id=project["id"],
        name=project["name"],
        description=project.get("description", ""),
        pack=raw.get("pack"),
        repository=repository,
    )


def resolve_workspace(root: Path) -> Workspace:
    """Load a workspace and its registered projects (workspace → projects → repos).

    Each project's `project.yaml` is resolved relative to the workspace root. A
    registered project whose directory or manifest is missing is a fail-closed
    error, not a silent skip — the manifest promised it exists.
    """
    root = root.resolve()
    layout = WorkspaceLayout.at(root)
    if not layout.manifest.is_file():
        raise NotFoundError(
            f"No workspace manifest at {layout.manifest}",
            detail="Run `projectos workspace init` to scaffold this directory.",
        )

    manifest = load_workspace_manifest(layout.manifest)

    resolved: list[ResolvedProject] = []
    for ref in manifest.projects:
        project_yaml = (root / ref.path / "project.yaml").resolve()
        if not project_yaml.is_file():
            raise ValidationError(
                f"Workspace registers project {ref.name!r} but {project_yaml} is missing",
                detail="Every registered project must have a project.yaml (fail-closed).",
            )
        resolved.append(ResolvedProject(ref, load_project_manifest(project_yaml)))

    return Workspace(root=root, manifest=manifest, projects=tuple(resolved))


# -- helpers -----------------------------------------------------------------


def _require_mapping(value: Any, *, source: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValidationError(
            f"{source} must contain a YAML mapping",
            detail=f"Found {type(value).__name__}.",
        )
    return value


def _reject_duplicates(names: Any, *, what: str) -> None:
    seen: set[str] = set()
    for name in names:
        if name in seen:
            raise ValidationError(f"Duplicate {what}: {name!r}")
        seen.add(name)
