#!/usr/bin/env bash
# Writes one founder-readable status file to AGENT-REPORTS. No secrets. No claims.
set -euo pipefail

REPORTS_DIR="${REPORTS_DIR:-/mnt/gdrive/AGENT-REPORTS}"
INBOX_DIR="${INBOX_DIR:-/home/projectos/gdrive-inbox}"
ENGINE_ENV="${ENGINE_ENV:-/etc/projectos/engine.env}"
STAMP="$(date +%Y-%m-%d_%H%M)"
DAY="$(date +%Y-%m-%d)"
OUT="${REPORTS_DIR}/FOUNDER-STATUS-${DAY}.md"

engine="codex"
if [[ -f "${ENGINE_ENV}" ]]; then
  engine="$(grep -E '^[[:space:]]*ENGINE=' "${ENGINE_ENV}" | tail -1 | cut -d= -f2- | tr -d '[:space:]' || true)"
  engine="${engine:-codex}"
fi

timer_line() {
  local u="$1"
  if systemctl is-active --quiet "$u" 2>/dev/null; then
    echo "active"
  else
    systemctl is-active "$u" 2>/dev/null || echo "unknown"
  fi
}

seats=(TRADEOS WEB AIW WARRANT PROJECTOS CHIEF EDUOS URJAOPS LEOS)
timer_block=""
any_bad=0
for s in "${seats[@]}"; do
  u="projectos-seat@${s}.timer"
  if systemctl cat "$u" &>/dev/null; then
    st=$(timer_line "$u")
    timer_block+="- ${u}: ${st}\n"
    [[ "$st" == "active" ]] || any_bad=1
  fi
done

signer=$(timer_line projectos-signer.timer)
[[ "$signer" == "active" ]] || any_bad=1

usage_today="none"
if [[ -f "${REPORTS_DIR}/FLEET-USAGE.md" ]]; then
  usage_today=$(grep -E "^${DAY} " "${REPORTS_DIR}/FLEET-USAGE.md" 2>/dev/null | tail -n 20 || true)
  [[ -n "${usage_today}" ]] || usage_today="none"
fi

failures="none"
if [[ -d "${REPORTS_DIR}" ]]; then
  mapfile -t fail_list < <(find "${REPORTS_DIR}" -maxdepth 1 -name '*WAKE-FAILURE*' -mtime -1 2>/dev/null | sort | tail -n 5 || true)
  if [[ ${#fail_list[@]} -gt 0 && -n "${fail_list[0]:-}" ]]; then
    failures=$(printf '%s\n' "${fail_list[@]}")
    any_bad=1
  fi
fi

inbox_open=0
inbox_names=""
scan_inbox() {
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  local p base
  while IFS= read -r -d '' p; do
    base=$(basename "$p")
    case "$base" in
      DONE-*|PROPOSAL_*) continue ;;
    esac
    inbox_open=$((inbox_open + 1))
    inbox_names+="- ${base}\n"
  done < <(find "$dir" -maxdepth 1 -type f -print0 2>/dev/null || true)
}
scan_inbox "${INBOX_DIR}"
scan_inbox "${REPORTS_DIR}/INBOX"

if [[ "$any_bad" -eq 0 ]]; then
  fleet="RUNNING"
elif [[ "$signer" != "active" ]]; then
  fleet="STOPPED_OR_DEGRADED"
else
  fleet="DEGRADED"
fi

needs="NONE"
if [[ "$failures" != "none" ]]; then
  needs="Inspect WAKE-FAILURE files listed below"
elif [[ "$signer" != "active" ]]; then
  needs="Re-enable projectos-signer.timer on droplet"
fi

{
  echo "FOUNDER STATUS — ${DAY} (${STAMP})"
  echo
  echo "1. Fleet: ${fleet}"
  echo "2. Engine default: ${engine}"
  echo "3. Signer timer: ${signer}"
  echo "4. Seat timers:"
  echo -e "${timer_block:-none registered}"
  echo "5. Usage today (last lines):"
  echo "${usage_today}"
  echo
  echo "6. Open INBOX files (non-DONE): ${inbox_open}"
  if [[ -n "${inbox_names}" ]]; then
    echo -e "${inbox_names}"
  fi
  echo "7. Failures (last 24h):"
  echo "${failures}"
  echo
  echo "8. Needs founder: ${needs}"
  echo
  echo "Generated by deploy/droplet/fleet-status.sh on $(hostname)"
} > "${OUT}.tmp"
mv -f "${OUT}.tmp" "${OUT}"
echo "Wrote ${OUT}"
